name: 'dbt_scd2_utils'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.0.0"]

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_scd2_utils
    search_order: ['dbt_scd2_utils', 'dbt']

vars:
  dbt_scd2_utils:
    # Default audit column names (can be overridden at model level)
    is_current_column: _is_current
    valid_from_column: _valid_from
    valid_to_column: _valid_to
    updated_at_column: updated_at
    change_type_column: _change_type
    # Default valid_to date for current records
    default_valid_to: "2999-12-31 23:59:59"
    # When true, exclude data that arrived after the dbt run started
    exclude_data_after_run_start: false